setup build strategy

diff --git a/.github/workflows/dev.yml b/.github/workflows/dev.yml
--- a/.github/workflows/dev.yml
+++ b/.github/workflows/dev.yml
@@ -6,43 +6,44 @@ on:
 
 name: Deploy Beta
 jobs:
-  # unit-tests:
-  #   name: Unit tests
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - uses: actions/checkout@v1
-  #     - uses: actions/setup-node@v1
-  #       with:
-  #         node-version: "10.x"
-  #     - name: Set tag name
-  #       run: |-
-  #         BUILD=$(git rev-list --count $GITHUB_SHA)
-  #         VERSION=$(node -e "p=require('./package.json');console.log(p.version)")
-  #         echo "::set-env name=CUSTOM_TAG::v${VERSION}.${BUILD}"
-  #     - name: Create GitHubRelease
-  #       uses: anothrNick/github-tag-action@master
-  #       env:
-  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  #         RELEASE_BRANCHES: "master"
-  #     - name: Cache node modules
-  #       uses: actions/cache@v1
-  #       id: cache
-  #       with:
-  #         path: node_modules
-  #         key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
-  #     - name: NPM install
-  #       run: npm i
-  #     - name: Generate icons
-  #       run: npm run generate-icons
-  #     - name: Run unit tests
-  #       run: npm test
-  #     - name: Upload coverage to Codecov
-  #       env:
-  #         CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
-  #       run: |-
-  #         curl -s https://codecov.io/bash | bash -s -- \
-  #         -F "unittests" \
-  #         -Z || echo 'Codecov upload failed'
+  unit-tests:
+    name: Unit tests
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v1
+      - uses: actions/setup-node@v1
+        with:
+          node-version: "10.x"
+      - name: Create Build tag
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |-
+          BUILD=$(git rev-list --count $GITHUB_SHA)
+          curl --request POST \
+               --url https://api.github.com/repos/moonlet/wallet-app/git/refs \
+               --header 'authorization: token $GITHUB_TOKEN' \
+               --header 'content-type: application/json' \
+               --data '{"ref": "refs/tags/build-$BUILD","sha": "$GITHUB_SHA"}'
+
+      - name: Cache node modules
+        uses: actions/cache@v1
+        id: cache
+        with:
+          path: node_modules
+          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
+      - name: NPM install
+        run: npm i
+      - name: Generate icons
+        run: npm run generate-icons
+      - name: Run unit tests
+        run: npm test
+      - name: Upload coverage to Codecov
+        env:
+          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
+        run: |-
+          curl -s https://codecov.io/bash | bash -s -- \
+          -F "unittests" \
+          -Z || echo 'Codecov upload failed'
   # beta-android:
   #   name: Android app
   #   runs-on: ubuntu-latest
@@ -126,7 +127,7 @@ jobs:
   beta-ext-chrome:
     name: Chrome extension
     runs-on: ubuntu-latest
-    # needs: unit-tests
+    needs: unit-tests
     steps:
       - uses: actions/setup-node@v1
         with:
